# Generated by Django 5.2.3 on 2025-08-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_news_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка'),
        ),
    ]
