# Generated by Django 5.2.3 on 2025-08-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='star',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Оценка'),
        ),
    ]
