# Generated by Django 5.0.14 on 2025-08-27 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('personal', 'Физическое лицо'), ('company', 'Юридическое лицо')], max_length=20, verbose_name='Тип верификации')),
                ('verification_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID верификации')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИО / Название компании')),
                ('inn', models.CharField(blank=True, max_length=20, null=True, verbose_name='ИНН / Регистрационный номер')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес регистрации')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Статус верификации')),
                ('passport_front', models.FileField(blank=True, null=True, upload_to='verifications/passports/', verbose_name='Паспорт (лицевая сторона)')),
                ('passport_back', models.FileField(blank=True, null=True, upload_to='verifications/passports/', verbose_name='Паспорт (оборотная сторона)')),
                ('registration_doc', models.FileField(blank=True, null=True, upload_to='verifications/registration/', verbose_name='Скан документа о регистрации')),
                ('license_doc', models.FileField(blank=True, null=True, upload_to='verifications/licenses/', verbose_name='Скан лицензии (при наличии)')),
                ('additional_doc', models.FileField(blank=True, null=True, upload_to='verifications/other/', verbose_name='Финансовая отчетность / доп. документ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Верификация',
                'verbose_name_plural': 'Верификации',
            },
        ),
    ]
