# Generated by Django 5.0.14 on 2025-08-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='is_verified',
            field=models.BooleanField(blank=True, null=True, verbose_name='Статус верификации'),
        ),
    ]
