# Generated by Django 5.0.14 on 2025-08-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_verification_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='is_verified',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Статус верификации'),
        ),
    ]
