# Generated by Django 5.0.14 on 2025-08-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_verification_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='player_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
