# Generated by Django 5.0.14 on 2025-09-01 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('currency', models.CharField(db_index=True, max_length=10)),
                ('network', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='finance_logos/')),
                ('decimal', models.PositiveIntegerField(default=8, help_text='Количество знаков после запятой')),
                ('min_amount', models.DecimalField(decimal_places=8, default=0.01, max_digits=20)),
                ('max_amount', models.DecimalField(decimal_places=8, default=1000.0, max_digits=20)),
                ('sell_fee', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('buy_fee', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('status_buy', models.BooleanField(default=True, help_text='Доступна для покупки')),
                ('status_sell', models.BooleanField(default=True, help_text='Доступна для продажи')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'ordering': ['currency', 'network'],
            },
        ),
        migrations.CreateModel(
            name='HistoryTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.IntegerField(unique=True, verbose_name='ID заявки')),
                ('amount_from', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Сумма списания')),
                ('amount_to', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Сумма зачисления')),
                ('rate', models.DecimalField(decimal_places=12, max_digits=30, verbose_name='Курс')),
                ('fee', models.DecimalField(decimal_places=3, default=0, max_digits=20, verbose_name='Комиссия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('type_of_change', models.CharField(choices=[('1', 'Ручная заявка'), ('2', 'Автоматическая')], max_length=25, verbose_name='Тип заявки')),
                ('invoice_to', models.CharField(blank=True, max_length=155, null=True, verbose_name='Счет получателя')),
                ('invoice_from', models.CharField(blank=True, max_length=155, null=True, verbose_name='Счет отправителя')),
                ('status', models.CharField(choices=[('1', 'Новая заявка'), ('2', 'Ожидание'), ('3', 'Завершено'), ('4', 'Отменено')], max_length=77, verbose_name='Статус')),
                ('currency_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_from', to='whitebitx.finance', verbose_name='Валюта списания (откуда)')),
                ('currency_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_to', to='whitebitx.finance', verbose_name='Валюта зачисления (куда)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История транзакции',
                'verbose_name_plural': 'Истории транзакций',
            },
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=12, default=0, max_digits=30)),
                ('fixed', models.DecimalField(decimal_places=12, default=0, max_digits=30)),
                ('rate_sell', models.DecimalField(decimal_places=10, default=1, max_digits=20)),
                ('rate_buy', models.DecimalField(decimal_places=10, default=1, max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency_f', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_from', to='whitebitx.finance')),
                ('currency_t', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_to', to='whitebitx.finance')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['currency_f', 'currency_t'],
            },
        ),
        migrations.AddConstraint(
            model_name='rates',
            constraint=models.UniqueConstraint(fields=('currency_f', 'currency_t'), name='unique_currency_pair'),
        ),
    ]
