# Generated by Django 5.2.3 on 2025-08-07 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='finance_logos/')),
                ('currency', models.CharField(max_length=10)),
                ('network', models.CharField(blank=True, max_length=50, null=True)),
                ('decimal', models.IntegerField(default=2)),
                ('min_amount', models.DecimalField(decimal_places=8, default=0.01, max_digits=20)),
                ('max_amount', models.DecimalField(decimal_places=8, default=1000.0, max_digits=20)),
                ('sell_fee', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('buy_fee', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('status_b', models.BooleanField(default=True)),
                ('status_s', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Finance',
                'verbose_name_plural': 'Finances',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_f', models.CharField(max_length=10)),
                ('currency_t', models.CharField(max_length=10)),
                ('rate_sell', models.DecimalField(decimal_places=20, default=1, max_digits=55)),
                ('rate_buy', models.DecimalField(decimal_places=20, default=1, max_digits=55)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='whitebitx.finance')),
            ],
            options={
                'verbose_name': 'Rate',
                'verbose_name_plural': 'Rates',
                'ordering': ['currency_f', 'currency_t'],
            },
        ),
    ]
