# Generated by Django 5.0.14 on 2025-09-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitebitx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historytransactions',
            name='total_amount',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=20, verbose_name='Сумма с учетом коммиссии'),
            preserve_default=False,
        ),
    ]
