# Generated by Django 5.2.3 on 2025-08-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitebitx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rates',
            name='rate_buy',
            field=models.DecimalField(decimal_places=10, default=1, max_digits=20),
        ),
        migrations.AlterField(
            model_name='rates',
            name='rate_sell',
            field=models.DecimalField(decimal_places=10, default=1, max_digits=20),
        ),
    ]
