# Generated by Django 5.0.14 on 2025-09-01 07:39

import assets.services.generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitebitx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historytransactions',
            name='expired',
            field=models.DateTimeField(blank=True, default=assets.services.generator.get_expired_time, null=True, verbose_name='Срок действия'),
        ),
    ]
