# Generated by Django 5.2.3 on 2025-08-07 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitebitx', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rates',
            name='finance',
        ),
        migrations.AlterField(
            model_name='rates',
            name='currency_f',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_f', to='whitebitx.finance'),
        ),
        migrations.AlterField(
            model_name='rates',
            name='currency_t',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_t', to='whitebitx.finance'),
        ),
    ]
