# Generated by Django 5.2.3 on 2025-08-13 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitebitx', '0002_alter_rates_rate_buy_alter_rates_rate_sell'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finance',
            options={'ordering': ['currency', 'network'], 'verbose_name': 'Валюта', 'verbose_name_plural': 'Валюты'},
        ),
        migrations.AlterModelOptions(
            name='rates',
            options={'ordering': ['currency_f', 'currency_t'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterField(
            model_name='finance',
            name='currency',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='finance',
            name='decimal',
            field=models.PositiveIntegerField(default=8, help_text='Количество знаков после запятой'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='network',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='finance',
            name='status_b',
            field=models.BooleanField(default=True, help_text='Доступна для покупки'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='status_s',
            field=models.BooleanField(default=True, help_text='Доступна для продажи'),
        ),
        migrations.AlterField(
            model_name='rates',
            name='currency_f',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_from', to='whitebitx.finance'),
        ),
        migrations.AlterField(
            model_name='rates',
            name='currency_t',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_to', to='whitebitx.finance'),
        ),
        migrations.AlterUniqueTogether(
            name='rates',
            unique_together={('currency_f', 'currency_t')},
        ),
    ]
