# Generated by Django 5.0.14 on 2025-09-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitebitx', '0002_historytransactions_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historytransactions',
            name='fee',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20, verbose_name='Комиссия'),
        ),
    ]
