# Generated by Django 5.0.14 on 2025-09-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitebitx', '0002_historytransactions_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historytransactions',
            name='expired',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок действия'),
        ),
    ]
