# Generated by Django 5.2.3 on 2025-08-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitebitx', '0002_remove_rates_finance_alter_rates_currency_f_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rates',
            name='rate_buy',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=55),
        ),
        migrations.AlterField(
            model_name='rates',
            name='rate_sell',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=55),
        ),
    ]
