# Generated by Django 5.0.14 on 2025-09-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitebitx', '0003_alter_historytransactions_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='historytransactions',
            name='inspection',
            field=models.IntegerField(default=0),
        ),
    ]
