# Generated by Django 5.2.3 on 2025-08-18 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitebitx', '0003_alter_finance_options_alter_rates_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finance',
            old_name='status_b',
            new_name='status_buy',
        ),
        migrations.RenameField(
            model_name='finance',
            old_name='status_s',
            new_name='status_sell',
        ),
        migrations.AlterUniqueTogether(
            name='rates',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rates',
            name='fixed',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rates',
            name='rate',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='rates',
            constraint=models.UniqueConstraint(fields=('currency_f', 'currency_t'), name='unique_currency_pair'),
        ),
    ]
