# Generated by Django 5.0.14 on 2025-08-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitebitx', '0004_rename_status_b_finance_status_buy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rates',
            name='fixed',
        ),
        migrations.AlterField(
            model_name='rates',
            name='rate',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=30),
        ),
    ]
