# Generated by Django 5.0.14 on 2025-09-10 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitebitx', '0004_historytransactions_inspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='fee',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='rates',
            name='fixed',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=30, verbose_name='Коммиссия'),
        ),
    ]
