# Generated by Django 5.0.14 on 2025-08-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitebitx', '0005_remove_rates_fixed_alter_rates_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rates',
            name='fixed',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=30),
        ),
    ]
