# Generated by Django 5.0.14 on 2025-08-28 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitebitx', '0007_historytransactions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historytransactions',
            options={'verbose_name': 'История транзакции', 'verbose_name_plural': 'Истории транзакций'},
        ),
        migrations.AlterField(
            model_name='finance',
            name='network',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='historytransactions',
            name='amount_from',
            field=models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Сумма списания'),
        ),
        migrations.AlterField(
            model_name='historytransactions',
            name='amount_to',
            field=models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Сумма зачисления'),
        ),
        migrations.AlterField(
            model_name='historytransactions',
            name='application_id',
            field=models.IntegerField(unique=True, verbose_name='ID заявки'),
        ),
        migrations.AlterField(
            model_name='historytransactions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='historytransactions',
            name='currency_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_from', to='whitebitx.finance', verbose_name='Валюта списания (откуда)'),
        ),
        migrations.AlterField(
            model_name='historytransactions',
            name='currency_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_to', to='whitebitx.finance', verbose_name='Валюта зачисления (куда)'),
        ),
        migrations.AlterField(
            model_name='historytransactions',
            name='fee',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='Комиссия'),
        ),
        migrations.AlterField(
            model_name='historytransactions',
            name='rate',
            field=models.DecimalField(decimal_places=12, max_digits=30, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='historytransactions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
